backend:
  branch: main
  # Use netlify identity as backend
  # name: git-gateway
  ### enable below lines for github integration ###
  name: github
  repo: aciccarello/ciccarello.me
media_folder: 'assets/img'
public_folder: '/assets/img'

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
slug:
  encoding: 'ascii'
  clean_accents: true
collections:
  - label: 'Blog'
    name: 'blog'
    label_singular: 'Post'
    folder: '_posts'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - label: 'Categories'
        name: 'categories'
        widget: 'hidden'
        default: 'blog'
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'string'
        required: false

      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Canonical URL',
          name: 'canonical_url',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'string',
          required: false,
        }
      - widget: list
        label: 'tags'
        name: 'tags'
        multiple: true
        allow_add: true
        required: false
      - {
          label: 'Main image',
          name: image,
          widget: image,
          required: false,
          allow_multiple: false,
        }
      - {
          label: 'Alt Text',
          name: 'image_alt',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Image Caption',
          name: 'image_caption',
          widget: 'string',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Settings'
    name: 'settings'
    editor:
      preview: false
    files:
      - label: 'Site'
        name: 'items'
        file: '_data/site.json'
        fields:
          - label: Title
            name: title
            widget: string
          - label: Nav Items
            name: header_pages
            widget: list
          - label: Description
            name: description
            widget: text
