backend:
  branch: main
  squash_merges: true
  # Use netlify identity as backend
  # name: git-gateway
  ### enable below lines for github integration ###
  name: github
  repo: aciccarello/ciccarello.me
media_folder: 'assets/img'
public_folder: '/assets/img'

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
slug:
  encoding: 'ascii'
  clean_accents: true
collections:
  - label: 'Blog'
    name: 'blog'
    label_singular: 'Post'
    folder: '_posts/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: blog/{{year}}/{{month}}/{{day}}/{{title}}
    editor:
      preview: false
    fields:
      - label: 'Categories'
        name: 'categories'
        widget: 'hidden'
        default: 'blog'
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'string'
        required: false

      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Canonical URL',
          name: 'canonical_url',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'string',
          required: false,
        }
      - widget: list
        label: 'tags'
        name: 'tags'
        multiple: true
        allow_add: true
        required: false
      - {
          label: 'Main image',
          name: image,
          widget: image,
          required: false,
          allow_multiple: false,
        }
      - {
          label: 'Alt Text',
          name: 'image_alt',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Image Caption',
          name: 'image_caption',
          widget: 'string',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Recipes'
    name: 'recipes'
    label_singular: 'Recipe'
    folder: '_posts/recipes'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: recipes/{{year}}/{{month}}/{{day}}/{{title}}
    editor:
      preview: false
    fields:
      - label: 'Categories'
        name: 'categories'
        widget: 'hidden'
        default: 'recipes'
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'string'
        required: false

      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Canonical URL',
          name: 'canonical_url',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'string',
          required: false,
        }
      - widget: list
        label: 'tags'
        name: 'tags'
        multiple: true
        allow_add: true
        required: false
      - {
          label: 'Main image',
          name: image,
          widget: image,
          required: false,
          allow_multiple: false,
        }
      - {
          label: 'Alt Text',
          name: 'image_alt',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Image Caption',
          name: 'image_caption',
          widget: 'string',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Photos'
    name: 'photos'
    label_singular: 'Photo'
    folder: '_posts/photos'
    create: true
    identifier_field: slug
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: photos/{{year}}/{{month}}/{{day}}/{{slug}}
    editor:
      preview: false
    fields:
      - label: 'Categories'
        name: 'categories'
        widget: 'hidden'
        default: 'photos'
      - { label: 'Slug', name: 'slug', widget: 'string', comment: 'This is used to create the url' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Canonical URL',
          name: 'canonical_url',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Permalink',
          name: 'permalink',
          widget: 'string',
          required: false,
          comment: 'This will override the "slug" option'
        }
      - widget: list
        label: 'tags'
        name: 'tags'
        multiple: true
        allow_add: true
        required: false
      - {
          label: 'Main image',
          name: image,
          widget: image,
          required: false,
          allow_multiple: false,
        }
      - {
          label: 'Alt Text',
          name: 'image_alt',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Image Caption',
          name: 'image_caption',
          widget: 'string',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Settings'
    name: 'settings'
    editor:
      preview: false
    files:
      - label: 'Site'
        name: 'items'
        file: '_data/site.json'
        fields:
          - label: Title
            name: title
            widget: string
          - label: Nav Items
            name: header_pages
            widget: list
          - label: Description
            name: description
            widget: text
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Colophon'
        name: 'colophon'
        file: 'colophon.md'
        preview_path: 'colophon'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Foster Care'
        name: 'foster'
        file: 'foster.liquid'
        preview_path: 'foster'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Privacy'
        name: 'privacy'
        file: 'privacy.md'
        preview_path: 'privacy'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Links'
        name: 'links'
        file: '_data/links.json'
        preview_path: 'links'
        fields:
          - { label: Description, name: description, widget: string }
          - label: Links
            name: links
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
      - label: 'Tags'
        name: 'tags'
        file: 'posts/tags/tags.json'
        preview_path: 'tags'
        fields:
          - label: Featured
            name: featured
            widget: list
            multiple: true
            allow_add: true
          - label: Descriptions
            summary: 'Text for tag pages. Add to config.yml to add page.'
            name: descriptions
            widget: object
            fields:
              - { label: 'Foster Care', name: 'foster care', widget: string }
              - { label: 'Birding', name: 'birding', widget: string }
              - { label: 'Dinners', name: 'dinners', widget: string }
              - { label: 'Travel', name: 'travel', widget: string }
